kind: ConfigMap
apiVersion: v1
metadata:
  name: ghost-nginx-config
data:
  default.conf: |-
    server {
      listen 80;

      location = /health {
        return 200 'OK';
      }

      location / {
        proxy_pass http://localhost:2368;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }


