apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blog.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "blog.name" . }}
    helm.sh/chart: {{ include "blog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "blog.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "blog.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf
              readOnly: false
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /
              port: http
        - name: ghost
          image: "{{ .Values.image.repository }}/blog:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: blog
              containerPort: 2368
              protocol: TCP
          env:
            - name: url
              value: {{ .Values.ghost.protocol }}://{{ .Values.ghost.host }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/usr/src/app/google-key.json"
          envFrom:
            - secretRef:
                name: blog-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/usr/src/app/google-key.json"
              name: serviceaccount
              readOnly: true
              subPath: google-key.json
      volumes:
        - name: nginx-conf
          configMap:
            name: blog-nginx-config
        - name: serviceaccount
          secret:
            secretName: "blog-serviceaccount"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
