kind: ConfigMap
apiVersion: v1
metadata:
  name: blog-nginx-config
data:
  default.conf: |-
    server {
      listen 80;

      location / {
        if ($http_x_forwarded_proto = "http") {
          return 301 https://$server_name$request_uri;
        }
        proxy_pass http://localhost:2368;
        proxy_set_header Host {{.Values.ghost.host}};
        proxy_set_header X-Forwarded-Proto {{.Values.ghost.protocol}};
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }


